# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740e22429442b2e8a1754a326e6c66a3ee5eaf9d4ecfa8c19e503feda6f5a4bac90e2cf480f9b94c596c33b0214bfb80e71e40586d87e6f6f676b80c0e229347

test:
  secret_key_base: 4d0516fb833943be06278619ce62897b8fbede7af4518d12f8ae1157ec334cd674884a795da4196a1e77ed1f1601eaf32e76fa17069a7761ec634b2e2cc9f269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
